# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20430f46a12839e3593d15465b005937573a5de09f88c381279263e7a35d9ad108131235255fb0469137fe71dc7561c986cfe3f4f495d491710b55a333fa4361

test:
  secret_key_base: 70be9d26322f7dc82622eaf39b791ad72f3d1f3af743821fe2aed6c9ef9e7efb5d6404cdc70bb3a7d9db61217b70acadc246f9c4eed1bca6fa96212c2a09e00a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
